apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api-namespace
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: andrejp02/api-image
        ports:
          - containerPort: 11000
        envFrom:
        - configMapRef:
            name: api-configmap
        env:
          - name: POSTGRES_DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret-api
                key: POSTGRES_DB_NAME

          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret-api
                key: POSTGRES_USER

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret-api
                key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: api-pod-service
  namespace: api-namespace
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: web
      port: 11000
      targetPort: 11000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: api-namespace
data:
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: postgres-service.postgres-sql-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-api
  namespace: api-namespace
type: Opaque
data:
  POSTGRES_DB_NAME: cG9zdGdyZXM=
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
