apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-check-deployment
  namespace: image-check-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-check-app
  template:
    metadata:
      labels:
        app: image-check-app
    spec:
      containers:
      - name: image-check-container
        imagePullPolicy: Always
        image: andrejp02/image-check
        ports:
          - containerPort: 12000
        envFrom:
          - configMapRef:
              name: image-check-configmap
        env:
          - name: MONGO_DB
            valueFrom:
              secretKeyRef:
                name: mongo-image-check
                key: MONGO_DB

          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-image-check
                key: MONGO_USERNAME

          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-image-check
                key: MONGO_PASSWORD
                
---
apiVersion: v1
kind: Service
metadata:
  name: image-check-service
  namespace:  image-check-namespace
  labels:
    app: image-check
spec:
  selector:
    app: image-check-app
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-check-configmap
  namespace: image-check-namespace
data: 
  DEPLOYMENT_NAME: node-server-app-vuln
  MONGO_HOST: mongo-service.mongo-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-image-check
  namespace: image-check-namespace
type: Opaque
data:
  MONGO_DB: bW9uZ29kYg==
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: cGFzc3dvcmQ=