apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios-deployment
  namespace: nagios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagios
  template:
    metadata:
      labels:
        app: nagios
    spec:
      containers:
        - name: nagios
          image: jasonrivers/nagios
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nagios-cfg-volume
              mountPath: /opt/nagios/etc/conf.d/auto-patch.cfg
              subPath: node-server-app.cfg
      volumes:
        - name: nagios-cfg-volume
          configMap:
            name: nagios-config
---
apiVersion: v1
kind: Service
metadata:
  name: nagios-service
  namespace: nagios
spec:
  selector:
    app: nagios
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nagios-config
  namespace: nagios
data:
  node-server-app.cfg: |
    define host {
      use linux-server
      host_name node-server-app
      address node-server-service.node-server-app.svc.cluster.local
    }

    define service {
      use generic-service
      host_name node-server-app
      service_description Service work on PORT 4000
      check_command check_http!-p 4000
    }

    define host {
      use linux-server
      host_name dummy-host
      address 192.0.2.123
    }

    define service{
      use generic-service
      host_name dummy-host
      service_description Dummy PING check
      check_command check_ping!100.0,20%!500.0,60%
    }